# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
